deploy:
  only:
    - main
  variables:
    DEPLOYMENT_DIR: "/home/gregq/deployed/onearth"
    ONEARTH_VERSION: "2.9.2"
    MRF_ARCHIVE_DIR: "/data/gregq/onearth/mrf-archive"
    FORCE_REDEPLOY: "true"
    TILE_SERVICES_PORT: "3180"
  script:
    - ./deploy.sh
