deploy:
  only:
    - main
  variables:
    ONEARTH_DEPLOY_FORCE: "true"
    ONEARTH_DEPLOY_DIR: "/home/gregq/deployed/onearth"
    MRF_ARCHIVE_DIR: "/data/gregq/onearth/mrf-archive"
    SHP_ARCHIVE_DIR: "/data/gregq/onearth/shp-archive"
    ONEARTH_PORT: "3180"
  script:
    - ./deploy.sh
